### ISSUE TITLE
php fatal: aufgabe bearbeiten

### ISSUE THREAD

**Issue by mglaubitz** [hrzbonn/Todolists#1]
hi, das sieht ja nach einem sehr spannenden plugin aus. hab das gerade mal ausprobiert und bekomme beim bearbeiten eine aufgabe mit ilias 5.2 folgenden fatal:

[Fri Oct 07 13:30:50.675505 2016] [php5:error] [pid 13111] [client 132.230.8.53:56933] PHP Fatal error:  Call to undefined method ilDateTimeInputGUI::setMode() in /srv/www/htdocs/ilias5_2_x/Customizing/global/plugins/Services/Repository/RepositoryObject/Todolists/classes/class.ilObjTodolistsGUI.php on line 413, referer: https://elearning14.ruf.uni-freiburg.de/ilias5_2_x/ilias.php?ref_id=90&cmd=post&cmdClass=ilobjtodolistsgui&cmdNode=29:4&baseClass=ilObjPluginDispatchGUI&rtoken=bc87ef8bebdadd07dd2e6c29fd076d4f
[Fri Oct 07 13:30:50.675665 2016] [php5:error] [pid 13111] [client 132.230.8.53:56933] Call to undefined method ilDateTimeInputGUI::setMode(), referer: https://elearning14.ruf.uni-freiburg.de/ilias5_2_x/ilias.php?ref_id=90&cmd=post&cmdClass=ilobjtodolistsgui&cmdNode=29:4&baseClass=ilObjPluginDispatchGUI&rtoken=bc87ef8bebdadd07dd2e6c29fd076d4f

**Comment by hrzbonn** [comment]
Hallo, danke für die Nutzung unseres Plugins. Leider unterstützt es derzeit maximal ILIAS 5.1.x. Selbstverständlich planen wir aber zukünftig auch eine Version für ILIAS 5.2 anzubieten. Sobald sie zur Verfügung steht, geben wir Ihnen Rückmeldung.

**Comment by hrzbonn** [comment]
Hallo, ab sofort unterstützt das Plugin auch ILIAS 5.2.

**Comment by fsesterh** [comment]
Hallo,
sieht nicht so aus, als wäre der Fehler mit 5.2 gefixed:

Whoops\Exception\ErrorException thrown with message "Call to undefined method ilDateTimeInputGUI::setMode()"

Stacktrace:
#0 Whoops\Exception\ErrorException in /var/www/html/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/Todolists/classes/class.ilObjTodolistsGUI.php:421

Auch bei mir tritt das auf, wenn ich eine angelegte Aufgabe bearbeiten möchte.

**Comment by hrzbonn** [comment]
Hallo und vielen Dank für die Nutzung unseres Plugins und den Hinweis auf den auftretenden Fehler. Der Fehler wurde jetzt behoben und die Korrekturen hochgeladen, sodass nun eine Fehlerfreie Nutzung möglich sein sollte.

**Comment by fsesterh** [comment]
Hallo,
vielen Dank für die blitzschnelle Reaktion und den Bugfix! Funktioniert jetzt.
