### ISSUE TITLE
Fehlende Sprachvariablen

### ISSUE THREAD

**Issue by fsesterh** [hrzbonn/Todolists#2]
Beim heutigen Testen des Plugins sind mir 2 Sprachvariablen aufgefallen, die scheinbar nicht befüllt sind oder nicht angelegt wurden (auch "Sprachen neu laden" ändert dies nicht):

obj_xtdo:
Erscheint z.B. im Dropdown Menü der Objektwahl unter Persönlicher Schreibtisch > Notizen und Kommentare

![26-06-_2017_15-26-59](https://user-images.githubusercontent.com/29703577/27541405-1863d1cc-5a84-11e7-8523-3667d9c8716b.png)

rep_robj_xtdo_xtdo_copy:
Das Recht eine Todo-Liste zu kopieren. Wenn man z.B. in der Rolle User die Berechtigungen für To-Do-Listen ändert, wird dort keine Beschreibung des Rechts, sondern nur der Identifier angezeigt.

![26-06-_2017_15-27-37](https://user-images.githubusercontent.com/29703577/27541408-1cba54d0-5a84-11e7-9b00-a586993b4548.png)

**Comment by hrzbonn** [comment]
Hallo und vielen Dank für den Hinweis auf den auftretenden Fehler. Nach längerem Suchen und Versuchen den Fehler bei den Notizen und Kommentaren zu beheben, ließ sich die Vermutung aufstellen, dass es sich dabei um einen Ilias internen Bug handelt, da dieser bei allen von uns getesteten anderen Plugins ebenfalls auftritt. Inzwischen haben wir den Fehler gemeldet. Der Bugreport ist unter https://www.ilias.de/mantis/view.php?id=20854 einsehbar. Dies hatte die leider verzögerte bzw. verlängerte Bearbeitungszeit zur Folge. Der Anzeige Fehler für das Kopieren einer Liste ließ sich jedoch beheben und sollte daher in der neuen Version nicht mehr auftreten.

**Comment by fsesterh** [comment]
Funktioniert, danke sehr!
