### ISSUE TITLE
Eindeutigkeit von Meilensteinen über alle Todo-Listen hinweg

### ISSUE THREAD

**Issue by fsesterh** [hrzbonn/Todolists#3]
Hallo,

ich kann einen Meilenstein nur 1x vergeben und zwar über alle To-Do-Listen hinweg. Der Meilenstein muss also global eineindeutig benannt sein. Ist das so beabsichtigt? Bspw. kann ich den Meilenstein "M1" in einer To-Do-Liste anlegen. Versuche ich dann in einer zweiten To-Do-Liste einen weiteren Meilenstein "M1" anzulegen bekomme ich diese Fehlermeldung:

![17-07-_2017_14-58-19](https://user-images.githubusercontent.com/29703577/28268963-91048842-6b00-11e7-8c18-68f1a983e191.png)

Ich bin auf diesem Stand:

commit c3c5185c4853c4217eef70fd1f29261af9ac653a
Author: hrzbonn <piseyb@uni-bonn.de>
Date:   Mon Jul 17 11:39:40 2017 +0200

    Entfernen der~ Datei

commit 564c64270b5daa476acc0f77bdeeed05efc90084
Author: hrzbonn <piseyb@uni-bonn.de>
Date:   Mon Jul 17 11:18:49 2017 +0200

    Anpassung der Sprachdatei

**Comment by hrzbonn** [comment]
Hallo und vielen Dank für den Hinweis. Gedacht war, dass der Meilenstein lokal in einer Todoliste nicht mehrmals erstellt werden kann, global über alle Todolisten sollte es jedoch möglich sein. Der Fehler wurde jetzt behoben und sollte ab jetzt nicht mehr auftreten.

**Comment by fsesterh** [comment]
Perfekt, funktioniert. Dankeschön.
