### ISSUE TITLE
Rechte für ToDo-Liste erst nach Sprachaktualisierung wählbar

### ISSUE THREAD

**Issue by MichelleKubier** [hrzbonn/Todolists#4]
Die neuen Rechte an der ToDo-Liste wie Aufgaben hinzufügen und Aufgaben bearbeiten sind nicht sichtbar (also auch nicht als unübersetzte Sprachvariable) solange die Sprache im Plugin nicht aktualisiert wurde. Dies ist ungünstig wenn man nicht weiß, dass es diese Rechte gibt, d.h. man kommt nach Installation des Plugins nicht auf den Gedanken, dass etwas fehlen könnte was erst nach Sprachaktualisierung sichtbar wird. D.h. diese Rechte sollten zumindest als nicht übersetzte Sprachvariable sofort sichtbar und in der Rollenverwaltung auswählbar sein.

**Comment by hrzbonn** [comment]
Hallo und vielen Dank für den Hinweis auf den auftretenden Fehler. Wir bekommen den Fehler derzeit nicht repoduziert. Welche Ilias Version nutzen Sie denn zurzeit?

**Comment by MichelleKubier** [comment]
Wir haben das Plugin unter 5.1. erstmalig im Einsatz.

**Comment by hrzbonn** [comment]
Vielen Dank. Der Fehler wurde behoben und sollte daher in der neuen Version nicht mehr auftreten.
