### ISSUE TITLE
Unvollständiger Einstellungs-Bereich nach Anlegen des Objekts

### ISSUE THREAD

**Issue by MichelleKubier** [hrzbonn/Todolists#6]
Nach dem Anlegen des Objekts Todo-Liste lande ich im Einstellungsreiter. Dieser zeigt jedoch nur Titel, Beschreibung und die Option für die Sammelliste. Auch F5 bringt hier interessanterweise nichts. Alle anderen Einstellungsmöglichkeiten inkl. die Option des Online-Schaltens findet man somit erst (zufällig), wenn man in einen anderen Reiter des Objekts geht und danach wieder nach "Einstellungen" zurückkehrt.
Da auch das rote "offline" unter dem Objekt-Titel fehlt, vergisst man also womöglich, das Objekt online zu schalten nachdem die Aufgaben erstellt wurden.
Getestet mit ILIAS 5.3.6
![todo_einstellungen_unvollstandig](https://user-images.githubusercontent.com/32267686/42825190-03fb12b8-89d1-11e8-9b65-29d00ea3fdf9.png)
.

**Comment by hrzbonn** [comment]
Hallo und vielen Dank für Ihre Meldung. Entschuldigen Sie bitte die verspätete Rückmeldung. Um die durch die Sammellisten entstehenden Daten konsistent zu halten ist es derzeit nötig, dass lediglich auf der Startseite die Einstellungsmöglichkeit Sammelliste zur Verfügung steht. Demnach soll die Möglichkeit der Bearbeitung aller Einstellungen erst gegeben sein, sobald bestimmt wurde ob es sich bei der zu erstellenden Liste um eine Sammelliste handelt.  Aus zeitlichen Gründen ist es uns derzeit leider nicht möglich an einer langfristigen Lösung zu arbeiten . Daher arbeiten wir an einer kurzfristigen Lösung. Wir werden eine entsprechende Hinweismeldung, sowie einen zweiten Button einfügen, welcher direkt nach dem speichern zu den Einstellungen weiterleitet.

**Comment by MichelleKubier** [comment]
Danke, das ist hilfreich.
